# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [1]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [2]:
import tensorflow as tf
print(tf.__version__)

2.1.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [0]:
from sklearn.datasets import load_iris
iris_df=load_iris()

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [0]:
import numpy as np
import pandas as pd


In [0]:
x=iris_df.data
y=iris_df.target

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [0]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.25,random_state=50)

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [0]:
from tensorflow.keras.utils import to_categorical

In [0]:
ytrain=to_categorical(ytrain,3)
ytest=to_categorical(ytest)

## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
Model_Seq=tf.keras.Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
from tensorflow.keras.layers import Dense

In [0]:
Model_Seq.add(Dense(4, activation='relu', input_shape=(4,)))
Model_Seq.add(Dense(4, activation='relu'))
Model_Seq.add(Dense(3, activation='softmax'))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:
Model_Seq.compile(loss='categorical_crossentropy',
              optimizer='SGD',
              metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [14]:
Model_Seq.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 4)                 20        
_________________________________________________________________
dense_1 (Dense)              (None, 4)                 20        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 15        
Total params: 55
Trainable params: 55
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [15]:
Model_Seq.fit(xtrain,ytrain,validation_data=(xtest,ytest),epochs=100)

Train on 112 samples, validate on 38 samples
Epoch 1/100
112/112 [==============================] - 1s 5ms/sample - loss: 1.5419 - accuracy: 0.3125 - val_loss: 1.3376 - val_accuracy: 0.3947
Epoch 2/100
112/112 [==============================] - 0s 183us/sample - loss: 1.3539 - accuracy: 0.3125 - val_loss: 1.2306 - val_accuracy: 0.3947
Epoch 3/100
112/112 [==============================] - 0s 163us/sample - loss: 1.2527 - accuracy: 0.3125 - val_loss: 1.1735 - val_accuracy: 0.3947
Epoch 4/100
112/112 [==============================] - 0s 179us/sample - loss: 1.1948 - accuracy: 0.3125 - val_loss: 1.1376 - val_accuracy: 0.3947
Epoch 5/100
112/112 [==============================] - 0s 170us/sample - loss: 1.1572 - accuracy: 0.3125 - val_loss: 1.1184 - val_accuracy: 0.3947
Epoch 6/100
112/112 [==============================] - 0s 177us/sample - loss: 1.1352 - accuracy: 0.3125 - val_loss: 1.1046 - val_accuracy: 0.3947
Epoch 7/100
112/112 [==============================] - 0s 155us/sample - lo

## Question 10

### Make predictions
- Predict labels on one row

In [16]:
Model_Seq.predict(xtest[0:1])

array([[0.12528256, 0.3591153 , 0.5156021 ]], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [17]:
ytest[0:1]

array([[0., 1., 0.]], dtype=float32)



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [19]:
import tensorflow as tf
print(tf.__version__)

2.1.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [26]:
# run this cell to upload file if you are using google colab
from google.colab import files
files.upload()

Saving prices.csv to prices.csv


In [0]:
price_df=pd.read_csv("prices.csv")

## Question 2

In [0]:
import numpy as np
import pandas as pd


### Drop columnns
- drop "date" and "symbol" column from the data

In [0]:
price_df1=price_df.drop(["date","symbol"],axis=1)

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [0]:
price_df2=price_df1.iloc[0:1000,:]

In [31]:
price_df2.shape

(1000, 5)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [0]:
X=price_df2.drop(["volume"],axis=1)
Y=price_df2["volume"]

In [0]:
Y=Y/1000000

In [34]:
Y.head()

0    2.1636
1    2.3864
2    2.4895
3    2.0063
4    1.4086
Name: volume, dtype: float64

In [35]:
X.dtypes

open     float64
close    float64
low      float64
high     float64
dtype: object

In [36]:
Y.dtypes

dtype('float64')

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [0]:
X=np.array(X)
Y=np.array(Y)
X=X.astype("float32")
Y=Y.astype("float32")

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [0]:
X=tf.math.l2_normalize(
    X,
    axis=None,
    epsilon=1e-12,
    name=None
)

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [0]:
R=tf.zeros(shape=(4,1))
S=tf.zeros(shape=(1))

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
@tf.function 
def prediction(features,R,S):
  Y_pred=tf.add(tf.matmul(features,R),S)
  return Y_pred

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
@tf.function
def loss(Y_actual,Y_predicted):
  diff=Y_actual-Y_predicted
  Sq=tf.square(diff)
  Avg=tf.reduce_mean(Sq)
  return Avg

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
def train(X,Y_actual,R,S,learning_rate=0.01):
  with tf.GradientTape() as t:
    t.watch([R,S])
    CP=prediction(X,R,S)
    CL=loss(Y_actual,CP)

  DW,DB=t.gradient(CL,[R,S])  

  R=R-learning_rate *DW
  S=S-learning_rate *DB

  return R,S 

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [45]:
for j in range(100):
  R,S=train(X,Y,R,S)
  print('Current Training loss on iteration',j,loss(Y,prediction(X,R,S)).numpy())

Current Training loss on iteration 0 236.16759
Current Training loss on iteration 1 235.09299
Current Training loss on iteration 2 234.06102
Current Training loss on iteration 3 233.06998
Current Training loss on iteration 4 232.11781
Current Training loss on iteration 5 231.20381
Current Training loss on iteration 6 230.32585
Current Training loss on iteration 7 229.48265
Current Training loss on iteration 8 228.67297
Current Training loss on iteration 9 227.89539
Current Training loss on iteration 10 227.14832
Current Training loss on iteration 11 226.43114
Current Training loss on iteration 12 225.74234
Current Training loss on iteration 13 225.0808
Current Training loss on iteration 14 224.44553
Current Training loss on iteration 15 223.835
Current Training loss on iteration 16 223.24931
Current Training loss on iteration 17 222.68655
Current Training loss on iteration 18 222.14595
Current Training loss on iteration 19 221.62688
Current Training loss on iteration 20 221.12842
Curre

### Observe values of Weight
- Print the updated values

In [46]:
print(R)

tf.Tensor(
[[0.05478281]
 [0.05488192]
 [0.05422736]
 [0.05533117]], shape=(4, 1), dtype=float32)


### Observe values of Bias
- Print the updated values

In [47]:
print(S)

tf.Tensor([4.607657], shape=(1,), dtype=float32)
